### ISSUE TITLE
/verify command crashes server because Java 8 does not support java.util.Optional.isEmpty()

### ISSUE THREAD

**Issue by nicwatson** [alexandre-lavoie/mccord#4]
Crash report: [crash-2021-02-09_18.24.19-server.txt](https://github.com/Concordia-Modding-Community/discochat/files/5955042/crash-2021-02-09_18.24.19-server.txt)

CommandVerify line 29 tries to call isEmpty() on an Optional. Java 11 has isEmpty() method but Java 8 doesn't seem to: https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

We're probably stuck with Java 8 because that's what the clients use and that's what most modders are (probably) compiling against. I think we just need to logically invert the check to use isPresent() instead.

**Comment by alexandre-lavoie** [comment]
Correct assumption - Java 8 really should've had that method...

**Comment by alexandre-lavoie** [comment]
Release 1.0.2 should fix this.
