### ISSUE TITLE
Account linking now sends a verification query in DM but seems to proceed as if verified anyway

### ISSUE THREAD

**Issue by nicwatson** [alexandre-lavoie/mccord#5]
Account linking now sends a verification query in DM but either it proceeds as if verified anyway, or listen and switch commands are not properly checking verification status.

With version 1.0.1

What I did:

- Deleted config/discochat.dat
- Started server
- Logged in as vapidincarnate
- Sent test message from MC to confirm unlinked status: message appeared from "vapidincarnate" in #game-chat
- Sent test message from Discord #staff to confirm unlinked status: message did not get forwarded to MC
- Used /discord link from MC to link account
- Did not reply to verification request DM
- /discord listen everything
- /discord switch staff
- Now able to see messages sent from #staff in MC, despite not verifying account link.

I was unable to use /verify to further troubleshoot from MC because of #4

**Comment by alexandre-lavoie** [comment]
Release 1.0.2 should fix this. Seems like I didn't consider checking what happened if the account wasn't fully linked... I'm opening #6 to prevent this from happening in the future.
