### ISSUE TITLE
/discord listen ignore does not work

### ISSUE THREAD

**Issue by nicwatson** [alexandre-lavoie/mccord#7]
/discord listen ignore can correctly predict/suggest channels, and if a valid channel is named, it will indicate command success, e.g. "/discord listen ignore losalamos" returns "Ignoring #losalamos."

However, messages from the ignored channel continue to be displayed.

This could probably get quite overwhelming if students are receiving in-game messages from main chat as well as every group channel.

**Comment by alexandre-lavoie** [comment]
e9259dc should fix this. Added throws not to allow inaccessible channels to be targeted. There is now an error which is the same for both valid visible/invisible or invalid channels - so it's impossible to find a channel name through guessing.
