### ISSUE TITLE
/discord listen add leaks entire channel list via completion suggestions

### ISSUE THREAD

**Issue by nicwatson** [alexandre-lavoie/mccord#8]
When linked to a non-admin Discord account, I can use "/discord listen add" and then scroll through the entire list of channels, including restricted ones, in the command completion suggestions. Additionally, I can issue the command to try listen to a channel to which I don't have access: the response will _say_ that the command was successful. However, testing so far has indicated that messages are not actually being sent from restricted channels to unauthorized users.

So the issue is twofold.
1. An information leak of the names of all channels on the server. I guess this isn't the end of the world, but it's not ideal.
2. A user-expectation issue in which a command appears to succeed but hasn't actually worked (in which case the intended behaviour is not for it to work, but for the message to say that it failed).

**Comment by alexandre-lavoie** [comment]
86f8e6b should fix this point 1 (user that don't have access should not see). By fixing point 1 - I believe it fixes point 2 (given we should not see the channel anymore). Will close for now.
